<?php

namespace Database\Seeders;

use App\Models\Cie10;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class Cie10Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $all = [['C50','Tumor maligno de la mama'],
        ['C51','Tumor maligno de la vulva'],
        ['C52','Tumor maligno de la vagina'],
        ['C53','Tumor maligno del cuello uterino'],
        ['C54','Tumor maligno del cuerpo del útero'],
        ['C55','Tumor maligno del órgano uterino no especificado'],
        ['C56','Tumor maligno del ovario'],
        ['C57','Tumor maligno de otros órganos genitales femeninos'],
        ['C58','Tumor maligno de los órganos genitales femeninos, no especificados'],
        ['N70','Salpingitis y ooforitis'],
        ['N71','Enfermedad inflamatoria del útero, excepto el cuello uterino'],
        ['N72','Inflamación del cuello uterino'],
        ['N73','Otras enfermedades inflamatorias de la vulva y de la vagina'],
        ['N74','Otras enfermedades inflamatorias de los órganos pélvicos femeninos'],
        ['N75','Enfermedad inflamatoria de la mama'],
        ['N76','Otras enfermedades inflamatorias del tejido mamario'],
        ['N77','Otras enfermedades inflamatorias del tejido mamario'],
        ['N80','Endometriosis'],
        ['N81','Prolapso genital femenino'],
        ['N82','Fistulas del tracto genital femenino'],
        ['N83','Otras enfermedades no inflamatorias de los órganos genitales femeninos'],
        ['N84','Policisto del ovario'],
        ['N85','Otros trastornos no inflamatorios del ovario, del trompa de Falopio y del ligamento ancho'],
        ['N86','Erosión (ulceración) del cuello uterino'],
        ['N87','Displasia del cuello uterino'],
        ['N88','Otros trastornos no inflamatorios del cuello uterino'],
        ['N89','Otros trastornos no inflamatorios del útero, excepto el cuello uterino'],
        ['N90','Trastornos no inflamatorios del ciclo menstrual'],
        ['N91','Menorragia'],
        ['N92','Amenorrea'],
        ['N93','Otras hemorragias uterinas anormales'],
        ['N94','Dolor y otros trastornos del ciclo menstrual y del sangrado perimenstrual'],
        ['N95','Síndrome del ovario poliquístico'],
        ['N96','Habitual aborto involuntario'],
        ['N97','Fallo repetido en la fecundación artificial'],
        ['N98','Otras afecciones del sistema reproductor femenino'],
        ['O00','Embarazo ectópico tubárico'],
        ['O01','Embarazo ectópico en el ovario'],
        ['O02','Embarazo ectópico en otras localizaciones especificadas'],
        ['O03','Aborto espontáneo incompleto'],
        ['O04','Aborto espontáneo completo'],
        ['O05','Otro aborto espontáneo'],
        ['O06','Aborto espontáneo con complicaciones no especificadas'],
        ['O07','Embarazo ectópico no especificado'],
        ['O08','Otras complicaciones del embarazo ectópico'],
        ['O10','Edema, proteinuria y trastornos hipertensivos en el embarazo'],
        ['O11','Edema, proteinuria y trastornos hipertensivos en el parto'],
        ['O12','Edema, proteinuria y trastornos hipertensivos en el puerperio'],
        ['O13','Hipertensión gestacional'],
        ['O14','Hipertensión crónica preexistente complicando el embarazo, el parto y el puerperio'],
        ['O15','Eclampsia'],
        ['O16','Otras enfermedades hipertensivas complicando el embarazo, el parto y el puerperio'],
        ['O20','Diabetes mellitus en el embarazo'],
        ['O21','Diabetes mellitus preexistente en el embarazo'],
        ['O22','Trastornos del metabolismo de los carbohidratos en el embarazo'],
        ['O23','Infección en el embarazo'],
        ['O24','Diabetes mellitus en trastornos endocrinos y metabólicos en el embarazo'],
        ['O25','Trastornos del sistema nervioso en el embarazo'],
        ['O26','Trastornos renales en el embarazo'],
        ['O28','Otras afecciones maternas relacionadas con el embarazo y con el aparato reproductor'],
        ['O30','Infección de las membranas y de los líquidos amnióticos en el embarazo'],
        ['O31','Otras enfermedades infecciosas específicas en el embarazo'],
        ['O32','Polihidramnios'],
        ['O33','Poliglobulia del recién nacido'],
        ['O34','Atención materna por presentación anormal del feto'],
        ['O35','Atención materna por malposición, presentación anormal y encajamiento del feto'],
        ['O36','Atención materna por signos reveladores de sufrimiento fetal'],
        ['O40','Polihidramnios y oligohidramnios'],
        ['O42','Rotura prematura de las membranas'],
        ['O43','Placenta previa'],
        ['O44','Otras hemorragias placentarias'],
        ['O45','Desprendimiento prematuro de la placenta'],
        ['O46','Trabajo de parto preterminado'],
        ['O47','Trabajo de parto prolongado'],
        ['O48','Otras complicaciones del trabajo de parto y del parto'],
        ['O60','Parto prematuro'],
        ['O61','Trabajo de parto prolongado y complicaciones del trabajo de parto'],
        ['O62','Trabajo de parto obstruido debido a la desproporción cefalopélvica'],
        ['O63','Sufrimiento fetal durante el trabajo de parto y el parto'],
        ['O64','Trabajo de parto obstruido debido a la presentación anormal del feto'],
        ['O65','Trabajo de parto obstruido debido a otras causas'],
        ['O66','Trabajo de parto prolongado sin motivo aparente'],
        ['O67','Trabajo de parto prolongado debido a obesidad'],
        ['O68','Trabajo de parto prolongado debido a otros motivos'],
        ['O69','Trabajo de parto prolongado, no especificado'],
        ['O70','Desgarro perineal durante el parto'],
        ['O71','Hemorragia en el postparto'],
        ['O72','Ruptura uterina durante el trabajo de parto'],
        ['O73','Retención de la cabeza del feto y de los hombros'],
        ['O74','Otras complicaciones del trabajo de parto y del parto, no clasificadas en otra parte'],
        ['O75','Enfermedades infecciosas del sistema reproductor en el puerperio'],
        ['O76','Otras complicaciones del puerperio, no clasificadas en otra parte'],
        ['O77','Trastornos cerebrovasculares en el puerperio'],
        ['O80','Parto único espontáneo en hospital o en el lugar de atención médica'],
        ['O81','Parto único espontáneo en el domicilio'],
        ['O82','Parto por cesárea'],
        ['O83','Parto asistido (con fórceps o ventosa)'],
        ['O84','Otros tipos de parto único espontáneo'],
        ['O85','Sepsis puerperal'],
        ['O86','Otros trastornos puerperales infecciosos'],
        ['O87','Tromboflebitis en el puerperio'],
        ['O88','Otros trastornos venosos en el puerperio'],
        ['O89','Otras complicaciones del puerperio no clasificadas en otra parte'],
        ['O90','Hemorragia del puerperio'],
        ['O91','Complicaciones del puerperio por aparato urinario'],
        ['O92','Otras complicaciones del puerperio, no clasificadas en otra parte'],
        ['O94','Muerte fetal'],
        ['O95','Desproporción materna y fetal'],
        ['O96','Muerte materna'],
        ['O97','Muertes múltiples debidas al embarazo, al parto y al puerperio'],
        ['O98','Otras enfermedades maternas clasificadas en otra parte'],
        ['O99','Otras enfermedades obstétricas y las no especificadas'],
        ['Z32','Supervisión de embarazo en el que se espera un nacimiento único'],
        ['Z33','Supervisión de embarazo en el que se espera un nacimiento múltiple'],
        ['Z34','Supervisión de embarazo con alto riesgo de complicaciones maternas'],
        ['Z35','Supervisión de embarazo con alto riesgo de complicaciones fetales'],
        ['Z36','Supervisión de otros embarazos de alto riesgo'],
        ['Z37','Vigilancia de término del parto'],
        ['Z38','Parto único espontáneo'],
        ['Z39','Vigilancia de parto por otros motivos'],
        ['Z40','Encuentros para la atención médica y el examen de rutina después del parto'],
        ['Z41','Atención a las mujeres en relación con procedimientos de reproducción asistida'],
        ['Z42','Atención a las mujeres en relación con la lactancia'],
        ['Z51','Encuentros para anticoncepción'],
    ];

    foreach($all as $a){

        Cie10::create([
            'codigo' => $a[1],
            'descripcion' => $a[0]
        ]);
    }

    }
}
