<?php

namespace Database\Seeders;

use App\Models\Cie10;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class Cie10Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

    $all = [
        ['B373', 'Candidiasis VV'],
        ['C50', 'Tumor maligno de la mama'],
        ['C51', 'Tumor maligno de la vulva'],
        ['C52', 'Tumor maligno de la vagina'],
        ['C53', 'Tumor maligno del cuello uterino'],
        ['C54', 'Tumor maligno del cuerpo del útero'],
        ['C55', 'Tumor maligno del órgano uterino no especificado'],
        ['C56', 'Tumor maligno del ovario'],
        ['C57', 'Tumor maligno de otros órganos genitales femeninos y de los no especificados'],
        ['C58', 'Tumor maligno de la placenta'],
        ['C97', 'Tumores malignos (primarios) de sitios multiples independientes'],
        ['D05', 'Carcinoma in situ de la mama'],
        ['D06', 'Carcinmo in situ del cuello del utero'],
        ['D07', 'Carcinoma in situ de otros organos genitales y de los no especificados'],
        ['D17', 'Tumores benignos lipomatosos'],
        ['D18', 'Hemangioma y linfangioma de cualquier sitio'],
        ['D19', 'Tumores benignos del tejido mesotelial'],
        ['D20', 'Tumor benigno del tejido blando del'],
        ['D21', 'Otros tumores benignos del tejido conjuntivo y de los tejidos blandos'],
        ['D24', 'Tumor benigno de la mama'],
        ['D25', 'Leiomioma del útero'],
        ['D26', 'Otros tumores benignos del útero'],
        ['D27', 'Tumor benigno del ovario'],
        ['D28', 'Tumor benigno de otros organos genitales femeninos y de los no especificados'],
        ['D29', 'Tumor benigno de los organos genitales masculinos'],
        ['D30', 'Tumor benigno de los organos urinarios'],
        ['D39', 'Tumor de comportamiento incierto o desconocido de los organos genitales femeninos'],
        ['D40', 'Tumor de comportamiento incierto o desconocido de los organos genitales masculinos'],
        ['D41', 'Tumor de comportamiento incierto o desconocido de los organos urinarios'],
        ['D259', 'Miomatosis Uterina'],
        ['E282', 'SOP'],
        ['G442', 'Cefalea Tensional'],
        ['M511', 'Lumbago + Radiculopatia'],
        ['M545', 'Lumbago'],
        ['N60', 'Displasia mamaria benigna'],
        ['N61', 'Trastornos inflamatorios de la mama'],
        ['N62', 'Hipertrofia de la mama'],
        ['N63', 'Masa no especificada en la mama'],
        ['N64', 'Otros trastornos de la mama'],
        ['N70', 'Salpingitis y ooforitis'],
        ['N71', 'Enfermedad inflamatoria del útero, excepto el cuello uterino'],
        ['N72', 'Inflamación del cuello uterino'],
        ['N73', 'Otras enfermedades inflamatorias de la vulva y de la vagina'],
        ['N74', 'Otras enfermedades inflamatorias de los órganos pélvicos femeninos'],
        ['N75', 'Enfermedades de la glandula de Bartholin'],
        ['N76', 'Otras enfermedades inflamatorias del tejido mamario'],
        ['N77', 'Ulceracion e inflamacion vulvovaginal en enfermedades clasificadas en otra parte'],
        ['N80', 'Endometriosis'],
        ['N81', 'Prolapso genital femenino'],
        ['N82', 'Fistulas del tracto genital femenino'],
        ['N83', 'Otros trastornos no inflamatorios del ovario, del trompa de Falopio y del ligamento ancho'],
        ['N84', 'Pólito del tracto genital femenino'],
        ['N85', 'Otras enfermedades no inflamatorias de los órganos genitales femeninos'],
        ['N86', 'Erosión (ulceración) del cuello uterino'],
        ['N87', 'Displasia del cuello uterino'],
        ['N88', 'Otros trastornos no inflamatorios del cuello uterino'],
        ['N89', 'Otros trastornos no inflamatorios de la vagina'],
        ['N90', 'Trastornos no inflamatorios del ciclo menstrual'],
        ['N91', 'Menstruacion ausenta, escasa o rara'],
        ['N92', 'Menstruacion excesiva, frecuente e irregular'],
        ['N93', 'Otras hemorragias uterinas anormales'],
        ['N94', 'Dolor y otros trastornos del ciclo menstrual y del sangrado perimenstrual'],
        ['N95', 'Otros trastornos menopausicos y perimenopausicos'],
        ['N96', 'Habitual aborto involuntario'],
        ['N97', 'Infertilidad femenina'],
        ['N98', 'Complicaciones asociadas con la fecundacion artificial'],
        ['N390', 'ITU'],
        ['N600', 'Quiste de Mama'],
        ['N644', 'Mastodinia'],
        ['N710', 'Cervicitis Aguda'],
        ['N711', 'Cervicitis Cronica'],
        ['N739', 'EPI'],
        ['N750', 'Quiste de Bartolino'],
        ['N751', 'Absceso de Bartolino'],
        ['N763', 'Vulvitis Subaguada Ycron'],
        ['N771', 'Vulvovaginitis'],
        ['N830', 'Quiste de Ovario'],
        ['N850', 'Hiperplasia endometrial'],
        ['N910', 'Amenorrea Primaria'],
        ['N911', 'Amenorrea Secundaria'],
        ['N928', 'Metrorragia'],
        ['N979', 'Infertilidad Secundaria'],
        ['O00', 'Embarazo ectópico tubárico'],
        ['O01', 'Embarazo ectópico en el ovario'],
        ['O02', 'Embarazo ectópico en otras localizaciones especificadas'],
        ['O03', 'Aborto espontáneo incompleto'],
    ['O04', 'Aborto espontáneo completo'],
    ['O05', 'Otro aborto espontáneo'],
    ['O06', 'Aborto espontáneo con complicaciones no especificadas'],
    ['O07', 'Embarazo ectópico no especificado'],
    ['O08', 'Otras complicaciones del embarazo ectópico'],
    ['O10', 'Edema, proteinuria y trastornos hipertensivos en el embarazo'],
    ['O11', 'Edema, proteinuria y trastornos hipertensivos en el parto'],
    ['O12', 'Edema, proteinuria y trastornos hipertensivos en el puerperio'],
    ['O13', 'Hipertensión gestacional'],
    ['O14', 'Hipertensión crónica preexistente complicando el embarazo, el parto y el puerperio'],
    ['O15', 'Eclampsia'],
    ['O16', 'Otras enfermedades hipertensivas complicando el embarazo, el parto y el puerperio'],
    ['O20', 'Diabetes mellitus en el embarazo'],
    ['O21', 'Diabetes mellitus preexistente en el embarazo'],
    ['O22', 'Trastornos del metabolismo de los carbohidratos en el embarazo'],
    ['O23', 'Infección en el embarazo'],
    ['O24', 'Diabetes mellitus en trastornos endocrinos y metabólicos en el embarazo'],
    ['O25', 'Trastornos del sistema nervioso en el embarazo'],
    ['O26', 'Trastornos renales en el embarazo'],
    ['O28', 'Otras afecciones maternas relacionadas con el embarazo y con el aparato reproductor'],
    ['O30', 'Infección de las membranas y de los líquidos amnióticos en el embarazo'],
    ['O31', 'Otras enfermedades infecciosas específicas en el embarazo'],
    ['O32', 'Polihidramnios'],
    ['O33', 'Poliglobulia del recién nacido'],
    ['O34', 'Atención materna por presentación anormal del feto'],
    ['O35', 'Atención materna por malposición, presentación anormal y encajamiento del feto'],
    ['O36', 'Atención materna por signos reveladores de sufrimiento fetal'],
    ['O40', 'Polihidramnios'],
    ['O41', 'Oligohidramnios'],
    ['O42', 'Rotura prematura de las membranas'],
    ['O43', 'Placenta previa'],
    ['O44', 'Otras hemorragias placentarias'],
    ['O45', 'Desprendimiento prematuro de la placenta'],
    ['O46', 'Trabajo de parto preterminado'],
    ['O47', 'Trabajo de parto prolongado'],
    ['O48', 'Otras complicaciones del trabajo de parto y del parto'],
    ['O60', 'Parto prematuro'],
    ['O61', 'Trabajo de parto prolongado y complicaciones del trabajo de parto'],
    ['O62', 'Trabajo de parto obstruido debido a la desproporción cefalopélvica'],
    ['O63', 'Sufrimiento fetal durante el trabajo de parto y el parto'],
    ['O64', 'Trabajo de parto obstruido debido a la presentación anormal del feto'],
    ['O65', 'Trabajo de parto obstruido debido a otras causas'],
    ['O66', 'Trabajo de parto prolongado sin motivo aparente'],
    ['O67', 'Trabajo de parto prolongado debido a obesidad'],
    ['O68', 'Trabajo de parto prolongado debido a otros motivos'],
    ['O69', 'Trabajo de parto prolongado, no especificado'],
    ['O70', 'Desgarro perineal durante el parto'],
    ['O71', 'Hemorragia en el postparto'],
    ['O72', 'Ruptura uterina durante el trabajo de parto'],
    ['O73', 'Retención de la cabeza del feto y de los hombros'],
    ['O74', 'Otras complicaciones del trabajo de parto y del parto, no clasificadas en otra parte'],
    ['O75', 'Enfermedades infecciosas del sistema reproductor en el puerperio'],
    ['O76', 'Otras complicaciones del puerperio, no clasificadas en otra parte'],
    ['O77', 'Trastornos cerebrovasculares en el puerperio'],
    ['O80', 'Parto único espontáneo en hospital o en el lugar de atención médica'],
    ['O81', 'Parto único espontáneo en el domicilio'],
    ['O82', 'Parto por cesárea'],
    ['O83', 'Parto asistido (con fórceps o ventosa)'],
    ['O84', 'Otros tipos de parto único espontáneo'],
    ['O85', 'Sepsis puerperal'],
    ['O86', 'Otros trastornos puerperales infecciosos'],
    ['O87', 'Tromboflebitis en el puerperio'],
    ['O88', 'Otros trastornos venosos en el puerperio'],
    ['O89', 'Otras complicaciones del puerperio no clasificadas en otra parte'],
    ['O90', 'Hemorragia del puerperio'],
    ['O91', 'Complicaciones del puerperio por aparato urinario'],
    ['O92', 'Otras complicaciones del puerperio, no clasificadas en otra parte'],
    ['O94', 'Muerte fetal'],
    ['O95', 'Desproporción materna y fetal'],
    ['O96', 'Muerte materna'],
    ['O97', 'Muertes múltiples debidas al embarazo, al parto y al puerperio'],
    ['O98', 'Otras enfermedades maternas clasificadas en otra parte'],
    ['O99', 'Otras enfermedades obstétricas y las no especificadas'],
    ['O150', 'Preeclampsia'],
    ['O200', 'Amenaza de aborto'],
    ['O221', 'Varices Vulnerables'],
    ['O331', 'Macrosomia Fetal'],
    ['O335', 'ICP'],
    ['O341', 'Cesarea Anterior'],
    ['O410', 'Placenta previa sin hemorragia'],
    ['O411', 'Placenta con hemorragia'],
    ['O912', 'Mastitis'],
    ['O990', 'Anemia y gestacion'],
    ['P050', 'RCIU'],
    ['Q831', 'Mamas Supernumerarias'],
    ['R103', 'Dolor Abdominal bajo'],
    ['Z014', 'Control Ginecologico'],
    ['Z27', 'Certificado Medico'],
    ['Z30', 'Anticoncepcion'],
    ['Z32', 'Supervisión de embarazo en el que se espera un nacimiento único'],
    ['Z33', 'Supervisión de embarazo en el que se espera un nacimiento múltiple'],
    ['Z34', 'Supervisión de embarazo con alto riesgo de complicaciones maternas'],
    ['Z35', 'Supervisión de embarazo con alto riesgo de complicaciones fetales'],
    ['Z36', 'Supervisión de otros embarazos de alto riesgo'],
    ['Z37', 'Vigilancia de término del parto'],
    ['Z38', 'Parto único espontáneo'],
    ['Z39', 'Vigilancia de parto por otros motivos'],
    ['Z40', 'Encuentros para la atención médica y el examen de rutina después del parto'],
    ['Z41', 'Atención a las mujeres en relación con procedimientos de reproducción asistida'],
    ['Z42', 'Atención a las mujeres en relación con la lactancia'],
    ['Z48', 'Cuidados post cirugia'],
    ['Z51', 'Procedimientos para la planificación de la familia'],
    ['Z51', 'Encuentros para anticoncepción'],
    ['Z302', 'Ligadura de trompas'],
    ['Z320', 'Embarazo aun no confirmado'],
    ['Z321', 'Embarazo confirmado'],
];

    foreach($all as $a){

        Cie10::create([
            'codigo' => $a[0],
            'descripcion' => $a[1]
        ]);
    }

    }
}
