<?php

namespace Database\Seeders;

use App\Models\Cie10;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class Cie10Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

    $all = [
        ['A00', 'Cólera'],
        ['A01', 'Fiebres tifoidea y paratifoidea'],
        ['A02', 'Otras infecciones debidas a Salmonella'],
        ['A03', 'Shigelosis'],
        ['A04', 'Otras infecciones intestinales bacterianas'],
        ['A05', 'Otras intoxicaciones alimentarias bacterianas'],
        ['A06', 'Amebiasis'],
        ['A07', 'Otras enfermedades intestinales debidas a protozoarios'],
        ['A08', 'Infecciones intestinales debidas a virus y otros organismos especificados'],
        ['A09', 'Diarrea y gastroenteritis de presunto origen infeccioso'],
        ['A15', 'Tuberculosis respiratoria, confirmada bacteriológica e histológicamente'],
        ['A16', 'Tuberculosis respiratoria, no confirmada bacteriológica o histológicamente'],
        ['A17', 'Tuberculosis del sistema nervioso'],
        ['A18', 'Tuberculosis de otros órganos'],
        ['A19', 'Tuberculosis miliar'],
        ['A20', 'Peste'],
        ['A21', 'Tularemia'],
        ['A22', 'Carbunco [ántrax]'],
        ['A23', 'Brucelosis'],
        ['A24', 'Muermo y melioidosis'],
        ['A25', 'Fiebres por mordedura de rata'],
        ['A26', 'Erisipeloide'],
        ['A27', 'Leptospirosis'],
        ['A28', 'Otras enfermedades zoonoticas bacterianas, no clasificadas en otra parte'],
        ['A30', 'Lepra [enfermedad de Hansen]'],
        ['A31', 'Infecciones debidas a otras micobacterias'],
        ['A32', 'Listeriosis'],
        ['A33', 'Tétanos neonatal'],
        ['A34', 'Tétanos obstétrico'],
        ['A35', 'Otros tétanos'],
        ['A36', 'Difteria'],
        ['A37', 'Tos ferina [tos convulsiva]'],
        ['A38', 'Escarlatina'],
        ['A39', 'Infección meningococica'],
        ['A40', 'Septicemia estreptococica'],
        ['A41', 'Otras septicemias'],
        ['A42', 'Actinomicosis'],
        ['A43', 'Nocardiosis'],
        ['A44', 'Bartonelosis'],
        ['A46', 'Erisipela'],
        ['A48', 'Otras enfermedades bacterianas, no clasificadas en otra parte'],
        ['A49', 'Infección bacteriana de sitio no especificado'],
        ['A50', 'Sífilis congénita'],
        ['A51', 'Sífilis precoz'],
        ['A52', 'Sífilis tardía'],
        ['A53', 'Otras sífilis y las no especificadas'],
        ['A54', 'Infección gonococica'],
        ['A55', 'Linfogranuloma (venéreo) por clamidias'],
        ['A56', 'Otras enfermedades de transmisión sexual debidas a clamidias'],
        ['A57', 'Chancro blando'],
        ['A58', 'Granuloma inguinal'],
        ['A59', 'Tricomoniasis'],
        ['A60', 'Infección anogenital debida a virus del herpes (herpes simple)'],
        ['A63', 'Otras enfermedades de transmisión predominantemente sexual, no clasificadas en otra parte'],
        ['A64', 'Enfermedad de transmisión sexual no especificada'],
        ['A65', 'Sífilis no venérea'],
        ['A66', 'Frambesia'],
        ['A67', 'Pinta [carate]'],
        ['A68', 'Fiebres recurrentes'],
        ['A69', 'Otras infecciones causadas por espiroquetas'],
        ['A70', 'Infección debida a Chlamydia psittaci'],
        ['A71', 'Tracoma'],
        ['A74', 'Otras enfermedades causadas por clamidias'],
        ['A75', 'Tifus'],
        ['A77', 'Fiebre maculosa (rickettsiosis transmitida por garrapatas)'],
        ['A78', 'Fiebre Q'],
        ['A79', 'Otras rickettsiosis'],
        ['A80', 'Poliomielitis aguda'],
        ['A81', 'Infecciones del sistema nervioso central por virus lento'],
        ['A82', 'Rabia'],
        ['A83', 'Encefalitis viral transmitida por mosquitos'],
        ['A84', 'Encefalitis viral transmitida por garrapatas'],
        ['A85', 'Otras encefalitis virales, no clasificadas en otra parte'],
        ['A86', 'Encefalitis viral, no especificada'],
        ['A87', 'Meningitis viral'],
        ['A88', 'Otras infecciones virales del sistema nervioso central, no clasificadas en otra parte'],
        ['A89', 'Infección viral del sistema nervioso central, no especificada'],
        ['A90', 'Fiebre del dengue [dengue clásico]'],
        ['A91', 'Fiebre del dengue hemorrágico'],
        ['A92', 'Otras fiebres virales transmitidas por mosquitos'],
        ['A93', 'Otras fiebres virales transmitidas por artrópodos, no clasificadas en otra parte'],
        ['A94', 'Fiebre viral transmitida por artrópodos, no especificada'],
        ['A95', 'Fiebre amarilla'],
        ['A96', 'Fiebre hemorrágica por arenavirus'],
        ['A98', 'Otras fiebres virales hemorrágicas, no clasificadas en otra parte'],
        ['A99', 'Fiebre viral hemorrágica, no especificada'],
        ['B00', 'Infecciones herpéticas [herpes simple]'],
        ['B01', 'Varicela'],
        ['B02', 'Herpes zoster'],
        ['B03', 'Viruela'],
        ['B04', 'Viruela de los monos'],
        ['B05', 'Sarampión'],
        ['B06', 'Rubeola [sarampión alemán]'],
        ['B07', 'Verrugas víricas'],
        ['B08', 'Otras infecciones víricas caracterizadas por lesiones de la piel y de las membranas mucosas, no clasificadas en otra parte'],
        ['B09', 'Infección viral no especificada, caracterizada por lesiones de la piel y de las membranas mucosas'],
        ['B15', 'Hepatitis aguda tipo A'],
        ['B16', 'Hepatitis aguda tipo B'],
        ['B17', 'Otras hepatitis virales agudas'],
        ['B18', 'Hepatitis viral crónica'],
        ['B19', 'Hepatitis viral, sin otra especificación'],
        ['B20', 'Enfermedad por virus de la inmunodeficiencia humana [VIH], resultante en enfermedades infecciosas y parasitarias'],
        ['B21', 'Enfermedad por virus de la inmunodeficiencia humana [VIH], resultante en tumores malignos'],
        ['B22', 'Enfermedad por virus de la inmunodeficiencia humana [VIH], resultante en otras enfermedades especificadas'],
        ['B23', 'Enfermedad por virus de la inmunodeficiencia humana [VIH], resultante en otras afecciones'],
        ['B24', 'Enfermedad por virus de la inmunodeficiencia humana [VIH], sin otra especificación'],
        ['B25', 'Enfermedad debida a virus citomegalico'],
        ['B26', 'Parotiditis infecciosa'],
        ['B27', 'Mononucleosis infecciosa'],
        ['B30', 'Conjuntivitis viral'],
        ['B33', 'Otras enfermedades virales, no clasificadas en otra parte'],
        ['B34', 'Infección viral de sitio no especificado'],
        ['B35', 'Dermatofitosis'],
        ['B36', 'Otras micosis superficiales'],
        ['B37', 'Candidiasis'],
        ['B38', 'Coccidioidomicosis'],
        ['B39', 'Histoplasmosis'],
        ['B40', 'Blastomicosis'],
        ['B41', 'Paracoccidioidomicosis'],
        ['B42', 'Esporotricosis'],
        ['B43', 'Cromomicosis y absceso feomicotico'],
        ['B44', 'Aspergilosis'],
        ['B45', 'Criptococosis'],
        ['B46', 'Cigomicosis'],
        ['B47', 'Micetoma'],
        ['B48', 'Otras micosis, no clasificadas en otra parte'],
        ['B49', 'Micosis, no especificada'],
        ['B50', 'Paludismo [malaria] debido a Plasmodium falciparum'],
        ['B51', 'Paludismo [malaria] debido a Plasmodium vivax'],
        ['B52', 'Paludismo [malaria] debido a Plasmodium malaria'],
        ['B53', 'Otro paludismo [malaria] confirmado parasitológicamente'],
        ['B54', 'Paludismo [malaria] no especificado'],
        ['B55', 'Leishmaniasis'],
        ['B56', 'Tripanosomiasis africana'],
        ['B57', 'Enfermedad de Chagas'],
        ['B58', 'Toxoplasmosis'],
        ['B59', 'Neumocistosis'],
        ['B60', 'Otras enfermedades debidas a protozoarios, no clasificadas en otra parte'],
        ['B64', 'Enfermedad debida a protozoarios, no especificada'],
        ['B65', 'Esquistosomiasis [bilharziasis]'],
        ['B66', 'Otras infecciones debidas a tremátodos'],
        ['B67', 'Equinococosis'],
        ['B68', 'Teniasis'],
        ['B69', 'Cisticercosis'],
        ['B70', 'Dofilobotriasis y esparganosis'],
        ['B71', 'Otras infecciones debidas a cestodos'],
        ['B72', 'Dracontiasis'],
        ['B73', 'Oncocercosis'],
        ['B74', 'Filariasis'],
        ['B75', 'Triquinosis'],
        ['B76', 'Anquilostomiasis y necatoriasis'],
        ['B77', 'Ascariasis'],
        ['B78', 'Estrongiloidiasis'],
        ['B79', 'Tricuriasis'],
        ['B80', 'Enterobiasis'],
        ['B81', 'Otras helmintiasis intestinales, no clasificadas en otra parte'],
        ['B82', 'Parasitosis intestinales, sin otra especificación'],
        ['B83', 'Otras helmintiasis'],
        ['B85', 'Pediculosis y pithiriasis'],
        ['B86', 'Escabiosis'],
        ['B87', 'Miasis'],
        ['B88', 'Otras infestaciones'],
        ['B89', 'Enfermedad parasitaria, no especificada'],
        ['B90', 'Secuelas de tuberculosis'],
        ['B91', 'Secuelas de poliomielitis'],
        ['B92', 'Secuelas de lepra'],
        ['B94', 'Secuelas de otras enfermedades infecciosas y parasitarias y de las no especificadas'],
        ['B95', 'Estreptococos y estafilococos como causa de enfermedades clasificadas en otros capítulos'],
        ['B96', 'Otros agentes bacterianos como causa de enfermedades clasificadas en otros capítulos'],
        ['B97', 'Agentes virales como causa de enfermedades clasificadas en otros capítulos'],
        ['B99', 'Otras enfermedades infecciosas y las no especificadas'],
        ['C00', 'Tumor maligno del labio'],
        ['C01', 'Tumor maligno de la base de la lengua'],
        ['C02', 'Tumor maligno de otras partes y de las no especificadas de la lengua'],
        ['C03', 'Tumor maligno de la encía'],
        ['C04', 'Tumor maligno del piso de la boca'],
        ['C05', 'Tumor maligno del paladar'],
        ['C06', 'Tumor maligno de otras partes y de las no especificadas de la boca'],
        ['C07', 'Tumor maligno de la glándula parótida'],
        ['C08', 'Tumor maligno de otras glándulas salivales mayores y de las no especificadas'],
        ['C09', 'Tumor maligno de la amígdala'],
        ['C10', 'Tumor maligno de la orofaringe'],
        ['C11', 'Tumor maligno de la nasofaringe'],
        ['C12', 'Tumor maligno del seno piriforme'],
        ['C13', 'Tumor maligno de la hipofaringe'],
        ['C14', 'Tumor maligno de otros sitios y de los mal definidos del labio, de la cavidad bucal y de la faringe'],
        ['C15', 'Tumor maligno del esófago'],
        ['C16', 'Tumor maligno del estómago'],
        ['C17', 'Tumor maligno del intestino delgado'],
        ['C18', 'Tumor maligno del colon'],
        ['C19', 'Tumor maligno de la unión rectosigmoidea'],
        ['C20', 'Tumor maligno del recto'],
        ['C21', 'Tumor maligno del ano y del conducto anal'],
        ['C22', 'Tumor maligno del hígado y de las vías biliares intrahepáticas'],
        ['C23', 'Tumor maligno de la vesícula biliar'],
        ['C24', 'Tumor maligno de otras partes y de las no especificadas de las vías biliares'],
        ['C25', 'Tumor maligno del páncreas'],
        ['C26', 'Tumor maligno de otros sitios y de los mal definidos de los órganos digestivos'],
        ['C30', 'Tumor maligno de las fosas nasales y del oído medio'],
        ['C31', 'Tumor maligno de los senos paranasales'],
        ['C32', 'Tumor maligno de la laringe'],
        ['C33', 'Tumor maligno de la tráquea'],
        ['C34', 'Tumor maligno de los bronquios y del pulmón'],
        ['C37', 'Tumor maligno del timo'],
        ['C38', 'Tumor maligno del corazón, del mediastino y de la pleura'],
        ['C39', 'Tumor maligno de otros sitios y de los mal definidos del sistema respiratorio y de los órganos intratorácicos'],
        ['C40', 'Tumor maligno de los huesos y de los cartílagos articulares de los miembros'],
        ['C41', 'Tumor maligno de los huesos y de los cartílagos articulares, de otros sitios y de sitios no especificados'],
        ['C43', 'Melanoma maligno de la piel'],
        ['C44', 'Otros tumores malignos de la piel'],
        ['C45', 'Mesotelioma'],
        ['C46', 'Sarcoma de Kaposi'],
        ['C47', 'Tumor maligno de los nervios periféricos y del sistema nervioso autónomo'],
        ['C48', 'Tumor maligno del peritoneo y del retroperitoneo'],
        ['C49', 'Tumor maligno de otros tejidos conjuntivos y de tejidos blandos'],
        ['C50', 'Tumor maligno de la mama'],
        ['C51', 'Tumor maligno de la vulva'],
        ['C52', 'Tumor maligno de la vagina'],
        ['C53', 'Tumor maligno del cuello del útero'],
        ['C54', 'Tumor maligno del cuerpo del útero'],
        ['C55', 'Tumor maligno del útero, parte no especificada'],
        ['C56', 'Tumor maligno del ovario'],
        ['C57', 'Tumor maligno de otros órganos genitales femeninos y de los no especificados'],
        ['C58', 'Tumor maligno de la placenta'],
        ['C60', 'Tumor maligno del pene'],
        ['C61', 'Tumor maligno de la próstata'],
        ['C62', 'Tumor maligno del testículo'],
        ['C63', 'Tumor maligno de otros órganos genitales masculinos y de los no especificados'],
        ['C64', 'Tumor maligno del riñón, excepto de la pelvis renal'],
        ['C65', 'Tumor maligno de la pelvis renal'],
        ['C66', 'Tumor maligno del uréter'],
        ['C67', 'Tumor maligno de la vejiga urinaria'],
        ['C68', 'Tumor maligno de otros órganos urinarios y de los no especificados'],
        ['C69', 'Tumor maligno del ojo y sus anexos'],
        ['C70', 'Tumor maligno de las meninges'],
        ['C71', 'Tumor maligno del encéfalo'],
        ['C72', 'Tumor maligno de la médula espinal, de los nervios craneales y de otras partes del sistema nervioso central'],
        ['C73', 'Tumor maligno de la glándula tiroides'],
        ['C74', 'Tumor maligno de la glándula suprarrenal'],
        ['C75', 'Tumor maligno de otras glándulas endocrinas y de estructuras afines'],
        ['C76', 'Tumor maligno de otros sitios y de sitios mal definidos'],
        ['C77', 'Tumor maligno secundario y el no especificado de los ganglios linfáticos'],
        ['C78', 'Tumor maligno secundario de los órganos respiratorios y digestivos'],
        ['C79', 'Tumor maligno secundario de otros sitios'],
        ['C80', 'Tumor maligno de sitios no especificados'],
        ['C81', 'Enfermedad de Hodgkin'],
        ['C82', 'Linfoma no Hodgkin folicular [nodular]'],
        ['C83', 'Linfoma no Hodgkin difuso'],
        ['C84', 'Linfoma de células T, periférico y cutáneo'],
        ['C85', 'Linfoma no Hodgkin de otro tipo y el no especificado'],
        ['C88', 'Enfermedades inmunoproliferativas malignas'],
        ['C90', 'Mieloma múltiple y tumores malignos de células plasmáticas'],
        ['C91', 'Leucemia linfoide'],
        ['C92', 'Leucemia mieloide'],
        ['C93', 'Leucemia monocítica'],
        ['C94', 'Otras leucemias de tipo celular especificado'],
        ['C95', 'Leucemia de células de tipo no especificado'],
        ['C96', 'Otros tumores malignos y los no especificados del tejido linfático, de los órganos hematopoyéticos y de tejidos afines'],
        ['C97', 'Tumores malignos (primarios) de sitios múltiples independientes'],
        ['D00', 'Carcinoma in situ de la cavidad bucal, del esófago y del estómago'],
        ['D01', 'Carcinoma in situ de otros órganos digestivos y de los no especificados'],
        ['D02', 'Carcinoma in situ del sistema respiratorio y del oído medio'],
        ['D03', 'Melanoma in situ'],
        ['D04', 'Carcinoma in situ de la piel'],
        ['D05', 'Carcinoma in situ de la mama'],
        ['D06', 'Carcinoma in situ del cuello del útero'],
        ['D07', 'Carcinoma in situ de otros órganos genitales y de los no especificados'],
        ['D09', 'Carcinoma in situ de otros sitios y de los no especificados'],
        ['D10', 'Tumor benigno de la boca y de la faringe'],
        ['D11', 'Tumor benigno de las glándulas salivales mayores'],
        ['D12', 'Tumor benigno del colon, del recto, del conducto anal y del ano'],
        ['D13', 'Tumor benigno de otras partes y de las mal definidas del sistema digestivo'],
        ['D14', 'Tumor benigno del oído medio y del sistema respiratorio'],
        ['D15', 'Tumor benigno de otros órganos intratorácicos y de los no especificados'],
        ['D16', 'Tumor benigno del hueso y del cartílago articular'],
        ['D17', 'Tumores benignos lipomatosos'],
        ['D18', 'Hemangioma y linfangioma de cualquier sitio'],
        ['D19', 'Tumores benignos del tejido mesotelial'],
        ['D20', 'Tumor benigno del tejido blando del peritoneo y del retroperitoneo'],
        ['D21', 'Otros tumores benignos del tejido conjuntivo y de los tejidos blandos'],
        ['D22', 'Nevo melanocítico'],
        ['D23', 'Otros tumores benignos de la piel'],
        ['D24', 'Tumor benigno de la mama'],
        ['D25', 'Leiomioma del útero'],
        ['D26', 'Otros tumores benignos del útero'],
        ['D27', 'Tumor benigno del ovario'],
        ['D28', 'Tumor benigno de otros órganos genitales femeninos y de los no especificados'],
        ['D29', 'Tumor benigno de los órganos genitales masculinos'],
        ['D30', 'Tumor benigno de los órganos urinarios'],
        ['D31', 'Tumor benigno del ojo y sus anexos'],
        ['D32', 'Tumores benignos de las meninges'],
        ['D33', 'Tumor benigno del encéfalo y de otras partes del sistema nervioso central'],
        ['D34', 'Tumor benigno de la glándula tiroides'],
        ['D35', 'Tumor benigno de otras glándulas endocrinas y de las no especificadas'],
        ['D36', 'Tumor benigno de otros sitios y de los no especificados'],
        ['D37', 'Tumor de comportamiento incierto o desconocido de la cavidad bucal y de los órganos digestivos'],
        ['D38', 'Tumor de comportamiento incierto o desconocido del oído medio y de los órganos respiratorios e intratoracicos'],
        ['D39', 'Tumor de comportamiento incierto o desconocido de los órganos genitales femeninos'],
        ['D40', 'Tumor de comportamiento incierto o desconocido de los órganos genitales masculinos'],
        ['D41', 'Tumor de comportamiento incierto o desconocido de los órganos urinarios'],
        ['D42', 'Tumor de comportamiento incierto o desconocido de las meninges'],
        ['D43', 'Tumor de comportamiento incierto o desconocido del encéfalo y del sistema nervioso central'],
        ['D44', 'Tumor de comportamiento incierto o desconocido de las glándulas endocrinas'],
        ['D45', 'Policitemia vera'],
        ['D46', 'Síndromes mielodisplasicos'],
        ['D47', 'Otros tumores de comportamiento incierto o desconocido del tejido linfático, de los órganos hematopoyeticos y de tejidos afines'],
        ['D48', 'Tumor de comportamiento incierto o desconocido de otros sitios y de los no especificados'],
        ['D50', 'Anemias por deficiencia de hierro'],
        ['D51', 'Anemia por deficiencia de vitamina B12'],
        ['D52', 'Anemia por deficiencia de folatos'],
        ['D53', 'Otras anemias nutricionales'],
        ['D55', 'Anemia debida a trastornos enzimáticos'],
        ['D56', 'Talasemia'],
        ['D57', 'Trastornos falciformes'],
        ['D58', 'Otras anemias hemoliticas hereditarias'],
        ['D59', 'Anemia hemolitica adquirida'],
        ['D60', 'Aplasia adquirida, exclusiva de la serie roja [eritroblastopenia]'],
        ['D61', 'Otras anemias aplásticas'],
        ['D62', 'Anemia posthemorragica aguda'],
        ['D63', 'Anemia en enfermedades crónicas clasificadas en otra parte'],
        ['D64', 'Otras anemias'],
        ['D65', 'Coagulación intravascular diseminada [síndrome de desfibrinacion]'],
        ['D66', 'Deficiencia hereditaria del factor VIII'],
        ['D67', 'Deficiencia hereditaria del factor IX'],
        ['D68', 'Otros defectos de la coagulación'],
        ['D69', 'Púrpura y otras afecciones hemorrágicas'],
        ['D70', 'Agranulocitosis'],
        ['D71', 'Trastornos funcionales de los polimorfonucleares neutrofilos'],
        ['D72', 'Otros trastornos de los leucocitos'],
        ['D73', 'Enfermedades del bazo'],
        ['D74', 'Metahemoglobinemia'],
        ['D75', 'Otras enfermedades de la sangre y de los órganos hematopoyeticos'],
        ['D76', 'Ciertas enfermedades que afectan al tejido linforreticular y al sistema reticuloendotelial'],
        ['D77', 'Otros trastornos de la sangre y de los órganos hematopoyeticos en enfermedades clasificadas en otra parte'],
        ['D80', 'Inmunodeficiencia con predominio de defectos de los anticuerpos'],
        ['D81', 'Inmunodeficiencias combinadas'],
        ['D82', 'Inmunodeficiencia asociada con otros defectos mayores'],
        ['D83', 'Inmunodeficiencia variable común'],
        ['D84', 'Otras inmunodeficiencias'],
        ['D86', 'Sarcoidosis'],
        ['D89', 'Otros trastornos que afectan el mecanismo de la inmunidad, no clasificados en otra parte'],
        ['E00', 'Síndrome congénito de deficiencia de yodo'],
        ['E01', 'Trastornos tiroideos vinculados a deficiencia de yodo y afecciones'],
        ['E02', 'Hipotiroidismo subclinico por deficiencia de yodo'],
        ['E03', 'Otro hipotiroidismo'],
        ['E04', 'Otro bocio no tóxico'],
        ['E05', 'Tirotoxicosis [hipertiroidismo]'],
        ['E06', 'Tiroiditis'],
        ['E07', 'Otros trastornos tiroideos'],
        ['E10', 'Diabetes mellitus insulinodependiente'],
        ['E11', 'Diabetes mellitus no insulinodependiente'],
        ['E12', 'Diabetes mellitus asociada con desnutrición'],
        ['E13', 'Otras diabetes mellitus especificadas'],
        ['E14', 'Diabetes mellitus, no especificada'],
        ['E15', 'Coma hipoglicemico no diabético'],
        ['E16', 'Otros trastornos de la secreción interna del páncreas'],
        ['E20', 'Hipoparatiroidismo'],
        ['E21', 'Hiperparatiroidismo y otros trastornos de la glándula paratiroides'],
        ['E22', 'Hiperfuncion de la glándula hipófisis'],
        ['E23', 'Hipofuncion y otros trastornos de la glándula hipófisis'],
        ['E24', 'Síndrome de Cushing'],
        ['E25', 'Trastornos adrenogenitales'],
        ['E26', 'Hiperaldosteronismo'],
        ['E27', 'Otros trastornos de la glándula suprarrenal'],
        ['E28', 'Disfunción ovarica'],
        ['E29', 'Disfunción testicular'],
        ['E30', 'Trastornos de la pubertad, no clasificados en otra parte'],
        ['E31', 'Disfunción poliglandular'],
        ['E32', 'Enfermedades del timo'],
        ['E34', 'Otros trastornos endocrinos'],
        ['E35', 'Trastornos endocrinos en enfermedades clasificadas en otra parte'],
        ['E40', 'Kwashiorkor'],
        ['E41', 'Marasmo nutricional'],
        ['E42', 'Kwashiorkor marasmatico'],
        ['E43', 'Desnutrición proteicocalorica severa, no especificada'],
        ['E44', 'Desnutrición proteicocalorica de grado moderado y leve'],
        ['E45', 'Retardo del desarrollo debido a desnutrición proteicocalorica'],
        ['E46', 'Desnutrición proteicocalorica, no especificada'],
        ['E50', 'Deficiencia de vitamina A'],
        ['E51', 'Deficiencia de tiamina'],
        ['E52', 'Deficiencia de niacina [pelagra]'],
        ['E53', 'Deficiencias de otras vitaminas del grupo B'],
        ['E54', 'Deficiencia de ácido ascorbico'],
        ['E55', 'Deficiencia de vitamina D'],
        ['E56', 'Otras deficiencias de vitaminas'],
        ['E58', 'Deficiencia dietética de calcio'],
        ['E59', 'Deficiencia dietética de selenio'],
        ['E60', 'Deficiencia dietética de zinc'],
        ['E61', 'Deficiencias de otros elementos nutricionales'],
        ['E63', 'Otras deficiencias nutricionales'],
        ['E64', 'Secuelas de la desnutrición y de otras deficiencias nutricionales'],
        ['E65', 'Adiposidad localizada'],
        ['E66', 'Obesidad'],
        ['E67', 'Otros tipos de hiperalimentación'],
        ['E68', 'Secuelas de hiperalimentación'],
        ['E70', 'Trastornos del metabolismo de los aminoácidos aromáticos'],
        ['E71', 'Trastornos del metabolismo de los aminoácidos de cadena ramificada y de los ácidos grasos'],
        ['E72', 'Otros trastornos del metabolismo de los aminoácidos'],
        ['E73', 'Intolerancia a la lactosa'],
        ['E74', 'Otros trastornos del metabolismo de los carbohidratos'],
        ['E75', 'Trastornos del metabolismo de los esfingolipidos y otros trastornos por almacenamiento de lípidos'],
        ['E76', 'Trastornos del metabolismo de los glucosamínoglicanos'],
        ['E77', 'Trastornos del metabolismo de las glucoproteinas'],
        ['E78', 'Trastornos del metabolismo de las lipoproteinas y otras lipidemias'],
        ['E79', 'Trastornos del metabolismo de las purinas y de las pirimidinas'],
        ['E80', 'Trastornos del metabolismo de las porfirinas y de la bilirrubina'],
        ['E83', 'Trastornos del metabolismo de los minerales'],
        ['E84', 'Fibrosis quistica'],
        ['E85', 'Amiloidosis'],
        ['E86', 'Deplecion del volumen'],
        ['E87', 'Otros trastornos de los líquidos, de los electrolitos y del equilibrio ácido-básico'],
        ['E88', 'Otros trastornos metabólicos'],
        ['E89', 'Trastornos endocrinos y metabólicos consecutivos a procedimientos, no clasificados en otra parte'],
        ['E90', 'Trastornos nutricionales y metabólicos en enfermedades clasificadas en otra parte'],
        ['F00', 'Demencia en la enfermedad de Alzheimer (G30.-+)'],
        ['F01', 'Demencia vascular'],
        ['F02', 'Demencia en otras enfermedades clasificadas en otra parte'],
        ['F03', 'Demencia, no especificada'],
        ['F04', 'Síndrome amnésico orgánico, no inducido por alcohol o por otras sustancias psicoactivas'],
        ['F05', 'Delirio, no inducido por alcohol o por otras sustancias psicoactivas'],
        ['F06', 'Otros trastornos mentales debidos a lesión y disfunción cerebral, y a enfermedad física'],
        ['F07', 'Trastornos de la personalidad y del comportamiento debidos a enfermedad, lesión o disfunción cerebral'],
        ['F09', 'Trastorno mental orgánico o sintomático, no especificado'],
        ['F20', 'Esquizofrenia'],
        ['F21', 'Trastorno esquizotipico'],
        ['F22', 'Trastornos delirantes persistentes'],
        ['F23', 'Trastornos psicoticos agudos y transitorios'],
        ['F24', 'Trastorno delirante inducido'],
        ['F25', 'Trastornos esquizoafectivos'],
        ['F28', 'Otros trastornos psicoticos de origen no orgánico'],
        ['F29', 'Psicosis de origen no orgánico, no especificada'],
        ['F30', 'Episodio maníaco'],
        ['F31', 'Trastorno afectivo bipolar'],
        ['F32', 'Episodio depresivo'],
        ['F33', 'Trastorno depresivo recurrente'],
        ['F34', 'Trastornos del humor [afectivos] persistentes'],
        ['F38', 'Otros trastornos del humor [afectivos]'],
        ['F39', 'Trastorno del humor [afectivo], no especificado'],
        ['F40', 'Trastornos fobicos de ansiedad'],
        ['F41', 'Otros trastornos de ansiedad'],
        ['F42', 'Trastorno obsesivo-compulsivo'],
        ['F43', 'Reacción al estrés grave y trastornos de adaptación'],
        ['F44', 'Trastornos disociativos [de conversión]'],
        ['F45', 'Trastornos somatomorfos'],
        ['F48', 'Otros trastornos neuróticos'],
        ['F50', 'Trastornos de la ingestión de alimentos'],
        ['F51', 'Trastornos no orgánicos del sueno'],
        ['F52', 'Disfunción sexual no ocasionada por trastorno ni enfermedad orgánicos'],
        ['F53', 'Trastornos mentales y del comportamiento asociados con el puerperio, no clasificados en otra parte'],
        ['F54', 'Factores psicológicos y del comportamiento asociados con trastornos o enfermedades clasificados en otra parte'],
        ['F55', 'Abuso de sustancias que no producen dependencia'],
        ['F59', 'Síndromes del comportamiento asociados con alteraciones fisiológicas y factores físicos, no especificados'],
        ['F60', 'Trastornos específicos de la personalidad'],
    ['F61', 'Trastornos mixtos y otros trastornos de la personalidad'],
    ['F62', 'Cambios perdurables de la personalidad, no atribuibles a lesión o a enfermedad cerebral'],
    ['F63', 'Trastornos de los hábitos y de los impulsos'],
    ['F64', 'Trastornos de la identidad de género'],
    ['F65', 'Trastornos de la preferencia sexual'],
    ['F66', 'Trastornos psicológicos y del comportamiento asociados con el desarrollo y con la orientación sexuales'],
    ['F68', 'Otros trastornos de la personalidad y del comportamiento en adultos'],
    ['F69', 'Trastorno de la personalidad y del comportamiento en adultos, no especificado'],
    ['F70', 'Retraso mental leve'],
    ['F71', 'Retraso mental moderado'],
    ['F72', 'Retraso mental grave'],
    ['F73', 'Retraso mental profundo'],
    ['F78', 'Otros tipos de retraso mental'],
    ['F79', 'Retraso mental, no especificado'],
    ['F80', 'Trastornos específicos del desarrollo del habla y del lenguaje'],
    ['F81', 'Trastornos específicos del desarrollo de las habilidades escolares'],
    ['F82', 'Trastorno específico del desarrollo de la función motriz'],
    ['F83', 'Trastornos específicos mixtos del desarrollo'],
    ['F84', 'Trastornos generalizados del desarrollo'],
    ['F88', 'Otros trastornos del desarrollo psicológico'],
    ['F89', 'Trastorno del desarrollo psicológico, no especificado'],
    ['F90', 'Trastornos hipercinéticos'],
    ['F91', 'Trastornos de la conducta'],
    ['F92', 'Trastornos mixtos de la conducta y de las emociones'],
    ['F93', 'Trastornos emocionales de comienzo específico en la niñez'],
    ['F94', 'Trastornos del comportamiento social de comienzo específico en la niñez y en la adolescencia'],
    ['F95', 'Trastornos por tics'],
    ['F98', 'Otros trastornos emocionales y del comportamiento que aparecen habitualmente en la niñez y en la adolescencia'],
    ['F99', 'Trastorno mental, no especificado'],
    ['G00', 'Meningitis bacteriana, no clasificada en otra parte'],
    ['G01', 'Meningitis en enfermedades bacterianas clasificadas en otra parte'],
    ['G02', 'Meningitis en otras enfermedades infecciosas y parasitarias clasificadas en otra parte'],
    ['G03', 'Meningitis debida a otras causas y a las no especificadas'],
    ['G04', 'Encefalitis, mielitis y encefalomielitis'],
    ['G05', 'Encefalitis, mielitis y encefalomielitis en enfermedades clasificadas en otra parte'],
    ['G06', 'Absceso y granuloma intracraneal e intrarraquídeo'],
    ['G07', 'Absceso y granuloma intracraneal e intrarraquídeo en enfermedades clasificadas en otra parte'],
    ['G08', 'Flebitis y tromboflebitis intracraneal e intrarraquídea'],
    ['G09', 'Secuelas de enfermedades inflamatorias del sistema nervioso central'],
    ['G10', 'Enfermedad de Huntington'],
    ['G11', 'Ataxia hereditaria'],
    ['G12', 'Atrofia muscular espinal y síndromes afines'],
    ['G13', 'Atrofias sistémicas que afectan primariamente el sistema nervioso central en enfermedades clasificadas en otra parte'],
    ['G20', 'Enfermedad de Parkinson'],
    ['G21', 'Parkinsonismo secundario'],
    ['G22', 'Parkinsonismo en enfermedades clasificadas en otra parte'],
    ['G23', 'Otras enfermedades degenerativas de los núcleos de la base'],
    ['G24', 'Distonía'],
    ['G25', 'Otros trastornos extrapiramidales y del movimiento'],
    ['G26', 'Trastornos extrapiramidales y del movimiento en enfermedades clasificadas en otra parte'],
    ['G30', 'Enfermedad de Alzheimer'],
    ['G31', 'Otras enfermedades degenerativas del sistema nervioso'],
    ['G32', 'Otros trastornos degenerativos del sistema nervioso en enfermedades clasificadas en otra parte'],
    ['G35', 'Esclerosis múltiple'],
    ['G36', 'Otras desmielinizaciones diseminadas agudas'],
    ['G37', 'Otras enfermedades desmielinizantes del sistema nervioso central'],
    ['G40', 'Epilepsia'],
    ['G41', 'Estado de mal epiléptico'],
    ['G43', 'Migraña'],
    ['G44', 'Otros síndromes de cefalea'],
    ['G45', 'Ataques de isquemia cerebral transitoria y síndromes afines'],
    ['G46', 'Síndromes vasculares encefálicos en enfermedades cerebrovasculares (I60-I67+)'],
    ['G47', 'Trastornos del sueño'],
    ['G50', 'Trastornos del nervio trigémino'],
    ['G51', 'Trastornos del nervio facial'],
    ['G52', 'Trastornos de otros nervios craneales'],
    ['G53', 'Trastornos de los nervios craneales en enfermedades clasificadas en otra parte'],
    ['G54', 'Trastornos de las raíces y de los plexos nerviosos'],
    ['G55', 'Compresiones de las raíces y de los plexos nerviosos en enfermedades'],
    ['G56', 'Mononeuropatías del miembro superior'],
    ['G57', 'Mononeuropatías del miembro inferior'],
    ['G58', 'Otras mononeuropatías'],
    ['G59', 'Mononeuropatía en enfermedades clasificadas en otra parte'],
    ['G60', 'Neuropatía hereditaria e idiopática'],
    ['G61', 'Polineuropatía inflamatoria'],
    ['G62', 'Otras polineuropatías'],
    ['G63', 'Polineuropatías en enfermedades clasificadas en otra parte'],
    ['G64', 'Otros trastornos del sistema nervioso periférico'],
    ['G70', 'Miastenia gravis y otros trastornos neuromusculares'],
    ['G71', 'Trastornos musculares primarios'],
    ['G72', 'Otras miopatías'],
    ['G73', 'Trastornos del músculo y de la unión neuromuscular en enfermedades clasificadas en otra parte'],
    ['G80', 'Parálisis cerebral infantil'],
    ['G81', 'Hemiplejía'],
    ['G82', 'Paraplejía y cuadriplejia'],
    ['G83', 'Otros síndromes paralíticos'],
    ['G90', 'Trastornos del sistema nervioso autónomo'],
    ['G91', 'Hidrocéfalo'],
    ['G92', 'Encefalopatía tóxica'],
    ['G93', 'Otros trastornos del encéfalo'],
    ['G94', 'Otros trastornos del encéfalo en enfermedades clasificadas en otra parte'],
    ['G95', 'Otras enfermedades de la médula espinal'],
    ['G96', 'Otros trastornos del sistema nervioso central'],
    ['G97', 'Trastornos del sistema nervioso consecutivos a procedimientos, no clasificados en otra parte'],
    ['G98', 'Otros trastornos del sistema nervioso, no clasificados en otra parte'],
    ['G99', 'Otros trastornos del sistema nervioso en enfermedades clasificadas en otra parte'],
    ['H00', 'Orzuelo y calacio'],
    ['H01', 'Otras inflamaciones del párpado'],
    ['H02', 'Otros trastornos de los párpados'],
    ['H03', 'Trastornos del párpado en enfermedades clasificadas en otra parte'],
    ['H04', 'Trastornos del aparato lagrimal'],
    ['H05', 'Trastornos de la órbita'],
    ['H06', 'Trastornos del aparato lagrimal y de la órbita en enfermedades clasificadas en otra parte'],
    ['H10', 'Conjuntivitis'],
    ['H11', 'Otros trastornos de la conjuntiva'],
    ['H13', 'Trastornos de la conjuntiva en enfermedades clasificadas en otra parte'],
    ['H15', 'Trastornos de la esclerótica'],
    ['H16', 'Queratitis'],
    ['H17', 'Opacidades y cicatrices corneales'],
    ['H18', 'Otros trastornos de la córnea'],
    ['H19', 'Trastornos de la esclerótica y de la córnea en enfermedades clasificadas en otra parte'],
    ['H20', 'Iridociclitis'],
    ['H21', 'Otros trastornos del iris y del cuerpo ciliar'],
    ['H22', 'Trastornos del iris y del cuerpo ciliar en enfermedades clasificadas en otra parte'],
    ['H25', 'Catarata senil'],
    ['H26', 'Otras cataratas'],
    ['H27', 'Otros trastornos del cristalino'],
    ['H28', 'Catarata y otros trastornos del cristalino en enfermedades clasificadas en otra parte'],
    ['H30', 'Inflamación coriorretiniana'],
    ['H31', 'Otros trastornos de la coroides'],
    ['H32', 'Trastornos coriorretinianos en enfermedades clasificadas en otra parte'],
    ['H33', 'Desprendimiento y desgarro de la retina'],
    ['H34', 'Oclusión vascular de la retina'],
    ['H35', 'Otros trastornos de la retina'],
    ['H36', 'Trastornos de la retina en enfermedades clasificadas en otra parte'],
    ['H40', 'Glaucoma'],
    ['H42', 'Glaucoma en enfermedades clasificadas en otra parte'],
    ['H43', 'Trastornos del cuerpo vítreo'],
    ['H44', 'Trastornos del globo ocular'],
    ['H45', 'Trastornos del globo ocular en enfermedades clasificadas en otra parte'],
    ['H46', 'Neuritis óptica'],
    ['H47', 'Otros trastornos del nervio óptico'],
    ['H48', 'Trastornos del nervio óptico y de las vías ópticas en enfermedades clasificadas en otra parte'],
    ['H49', 'Parálisis del músculo motor ocular'],
    ['H50', 'Otros estrabismos'],
    ['H51', 'Otros trastornos de los movimientos binoculares'],
    ['H52', 'Trastornos de la refracción y de la acomodación'],
    ['H53', 'Trastornos de la función visual'],
    ['H54', 'Ceguera y disminución de la agudeza visual'],
    ['H55', 'Nistagmo y otros movimientos oculares irregulares'],
    ['H57', 'Otros trastornos del ojo y sus anexos'],
    ['H58', 'Otros trastornos del ojo y sus anexos en enfermedades clasificadas en otra parte'],
    ['H59', 'Trastornos del ojo y sus anexos consecutivos a procedimientos, no clasificados en otra parte'],
    ['H60', 'Otitis externa'],
    ['H61', 'Otros trastornos del oído externo'],
    ['H62', 'Trastornos del oído externo en enfermedades clasificadas en otra parte'],
    ['H65', 'Otitis media no supurativa'],
    ['H66', 'Otitis media supurativa y no especificada'],
    ['H67', 'Otitis media en enfermedades clasificadas en otra parte'],
    ['H68', 'Inflamación y obstrucción de la trompa de Eustaquio'],
    ['H69', 'Otros trastornos de la trompa de Eustaquio'],
    ['H70', 'Mastoiditis y afecciones relacionadas'],
    ['H71', 'Colesteatoma del oído medio'],
    ['H72', 'Perforación de la membrana timpánica'],
    ['H73', 'Otros trastornos de la membrana timpánica'],
    ['H74', 'Otros trastornos del oído medio y de la apófisis mastoides'],
    ['H75', 'Otros trastornos del oído medio y de la apófisis mastoides en enfermedades clasificadas en otra parte'],
    ['H80', 'Otosclerosis'],
    ['H81', 'Trastornos de la función vestibular'],
    ['H82', 'Síndromes vertiginosos en enfermedades clasificadas en otra parte'],
    ['H83', 'Otros trastornos del oído interno'],
    ['H90', 'Hipoacusia conductiva y neurosensorial'],
    ['H91', 'Otras hipoacusias'],
    ['H92', 'Otalgia y secreción del oído'],
    ['H93', 'Otros trastornos del oído, no clasificados en otra parte'],
    ['H94', 'Otros trastornos del oído en enfermedades clasificadas en otra parte'],
    ['H95', 'Trastornos del oído y de la apófisis mastoides consecutivos a procedimientos, no clasificados en otra parte'],
    ['I00', 'Fiebre reumática sin mención de compromiso del corazón'],
    ['I01', 'Fiebre reumática con compromiso del corazón'],
    ['I02', 'Corea reumática'],
    ['I05', 'Enfermedades reumáticas de la válvula mitral'],
    ['I06', 'Enfermedades reumáticas de la válvula aórtica'],
    ['I07', 'Enfermedades reumáticas de la válvula tricúspide'],
    ['I08', 'Enfermedades de múltiples válvulas cardíacas'],
    ['I09', 'Otras enfermedades reumáticas del corazón'],
    ['I10', 'Hipertensión esencial (primaria)'],
    ['I11', 'Enfermedad cardíaca hipertensiva'],
    ['I12', 'Enfermedad renal hipertensiva'],
    ['I13', 'Enfermedad cardíaca y renal hipertensiva'],
    ['I15', 'Hipertensión secundaria'],
    ['I20', 'Angina de pecho'],
    ['I21', 'Infarto agudo de miocardio'],
    ['I22', 'Infarto recurrente de miocardio'],
    ['I23', 'Ciertas complicaciones actuales consecutivas a infarto agudo de miocardio'],
    ['I24', 'Otras enfermedades isquémicas agudas del corazón'],
    ['I25', 'Enfermedad isquémica crónica del corazón'],
    ['I26', 'Embolia pulmonar'],
    ['I27', 'Otras enfermedades pulmonares del corazón'],
    ['I28', 'Otras enfermedades del sistema arterial pulmonar'],
    ['I30', 'Pericarditis aguda'],
    ['I31', 'Otras enfermedades del pericardio'],
    ['I32', 'Pericarditis en enfermedades clasificadas en otra parte'],
    ['I33', 'Endocarditis aguda y subaguda'],
    ['I34', 'Trastornos no reumáticos de la válvula mitral'],
    ['I35', 'Trastornos no reumáticos de la válvula aórtica'],
    ['I36', 'Trastornos no reumáticos de la válvula tricúspide'],
    ['I37', 'Trastornos no reumáticos de la válvula pulmonar'],
    ['I38', 'Endocarditis, válvula no especificada'],
    ['I39', 'Endocarditis y enfermedades valvulares en enfermedades clasificadas en otra parte'],
    ['I40', 'Miocarditis aguda'],
    ['I41', 'Miocarditis en enfermedades clasificadas en otra parte'],
    ['I42', 'Cardiomiopatía'],
    ['I43', 'Cardiomiopatía en enfermedades clasificadas en otra parte'],
    ['I44', 'Bloqueo auriculoventricular y de rama izquierda'],
    ['I45', 'Otros trastornos de la conducción'],
    ['I46', 'Paro cardíaco'],
    ['I47', 'Taquicardia paroxística'],
    ['I48', 'Fibrilación y aleteo auricular'],
    ['I49', 'Otras arritmias cardíacas'],
    ['I50', 'Insuficiencia cardíaca'],
    ['I51', 'Complicaciones y trastornos mal definidos de la enfermedad cardíaca'],
    ['I52', 'Otras enfermedades del corazón en enfermedades clasificadas en otra parte'],
    ['I60', 'Hemorragia subaracnoidea'],
    ['I61', 'Hemorragia intracerebral'],
    ['I62', 'Otras hemorragias intracraneales no traumáticas'],
    ['I63', 'Infarto cerebral'],
    ['I64', 'Accidente cerebrovascular, no especificado como hemorrágico o isquémico'],
    ['I65', 'Oclusión y estenosis de las arterias precerebrales, no provocando infarto cerebral'],
    ['I66', 'Oclusión y estenosis de las arterias cerebrales, no provocando infarto cerebral'],
    ['I67', 'Otras enfermedades cerebrovasculares'],
    ['I68', 'Enfermedades cerebrovasculares en enfermedades clasificadas en otra parte'],
    ['I69', 'Secuelas de enfermedades cerebrovasculares'],
    ['I70', 'Ateroesclerosis'],
    ['I71', 'Aneurisma y disección aórticos'],
    ['I72', 'Aneurisma y disección de otras arterias'],
    ['I73', 'Otras enfermedades vasculares periféricas'],
    ['I74', 'Embolia y trombosis arteriales'],
    ['I77', 'Otros trastornos arteriales y arteriolares'],
    ['I78', 'Enfermedades de los capilares'],
    ['I79', 'Trastornos de las arterias, arteriolas y capilares en enfermedades clasificadas en otra parte'],
    ['I80', 'Flebitis y tromboflebitis'],
    ['I81', 'Trombosis de la vena porta'],
    ['I82', 'Embolia y trombosis de otras venas'],
    ['I83', 'Várices de los miembros inferiores'],
    ['I84', 'Hemorroides'],
    ['I85', 'Várices esofágicas'],
    ['I86', 'Várices de otras localizaciones'],
    ['I87', 'Otras enfermedades de las venas'],
    ['I88', 'Linfadenitis no especificada'],
    ['I89', 'Otros trastornos no infecciosos de los vasos linfáticos y ganglios linfáticos'],
    ['I95', 'Hipotensión'],
    ['I97', 'Trastornos del sistema circulatorio consecutivos a procedimientos, no clasificados en otra parte'],
    ['I98', 'Otros trastornos del sistema circulatorio en enfermedades clasificadas en otra parte'],
    ['I99', 'Otros trastornos y los no especificados del sistema circulatorio'],
    ['J00', 'Nasofaringitis aguda [resfrío común]'],
    ['J01', 'Sinusitis aguda'],
    ['J02', 'Faringitis aguda'],
    ['J03', 'Amigdalitis aguda'],
    ['J04', 'Laringitis y traqueítis agudas'],
    ['J05', 'Laringitis obstructiva aguda [crup] y epiglotitis'],
    ['J06', 'Infecciones agudas de las vías respiratorias superiores de sitios múltiples y no especificados'],
    ['J09', 'Gripe debida a ciertos virus de la gripe identificados'],
    ['J10', 'Influenza debida a virus de la influenza identificado'],
    ['J11', 'Influenza debida a virus no identificado'],
    ['J12', 'Neumonía viral, no clasificada en otra parte'],
    ['J13', 'Neumonía debida a Streptococcus pneumoniae'],
    ['J14', 'Neumonía debida a Haemophilus influenzae'],
    ['J15', 'Neumonía bacteriana, no clasificada en otra parte'],
    ['J16', 'Neumonía debida a otros microorganismos infecciosos, no clasificados en otra parte'],
    ['J17', 'Neumonía en enfermedades clasificadas en otra parte'],
    ['J18', 'Neumonía, organismo no especificado'],
    ['J20', 'Bronquitis aguda'],
    ['J21', 'Bronquiolitis aguda'],
    ['J22', 'Infección aguda no especificada de las vías respiratorias inferiores'],
    ['J30', 'Rinitis alérgica y vasomotora'],
    ['J31', 'Rinitis, rinofaringitis y faringitis crónicas'],
    ['J32', 'Sinusitis crónica'],
    ['J33', 'Pólipo nasal'],
    ['J34', 'Otros trastornos de la nariz y de los senos paranasales'],
    ['J35', 'Enfermedades crónicas de las amígdalas y de las adenoides'],
    ['J36', 'Absceso periamigdalino'],
    ['J37', 'Laringitis y laringotraqueitis crónicas'],
    ['J38', 'Enfermedades de las cuerdas vocales y de la laringe, no clasificadas en otra parte'],
    ['J39', 'Otras enfermedades de las vías respiratorias superiores'],
    ['J40', 'Bronquitis, no especificada como aguda o crónica'],
    ['J41', 'Bronquitis crónica simple y mucopurulenta'],
    ['J42', 'Bronquitis crónica no especificada'],
    ['J43', 'Enfisema'],
    ['J44', 'Otras enfermedades pulmonares obstructivas crónicas'],
    ['J45', 'Asma'],
    ['J46', 'Estado asmático'],
    ['J47', 'Bronquiectasia'],
    ['J60', 'Neumoconiosis de los mineros del carbón'],
    ['J61', 'Neumoconiosis debida al asbesto y a otras fibras minerales'],
    ['J62', 'Neumoconiosis debida a polvo de sílice'],
    ['J63', 'Neumoconiosis debida a otros polvos inorgánicos'],
    ['J64', 'Neumoconiosis, no especificada'],
    ['J65', 'Neumoconiosis asociada con tuberculosis'],
    ['J66', 'Enfermedades de las vías aéreas debidas a polvos orgánicos específicos'],
    ['J67', 'Neumonitis debida a hipersensibilidad al polvo orgánico'],
    ['J68', 'Afecciones respiratorias debidas a inhalación de gases, humos, vapores y sustancias químicas'],
    ['J69', 'Neumonitis debida a sólidos y líquidos'],
    ['J70', 'Afecciones respiratorias debidas a otros agentes externos'],
    ['J80', 'Síndrome de dificultad respiratoria del adulto'],
    ['J81', 'Edema pulmonar'],
    ['J82', 'Eosinofilia pulmonar, no clasificada en otra parte'],
    ['J84', 'Otras enfermedades pulmonares intersticiales'],
    ['J85', 'Absceso del pulmón y del mediastino'],
    ['J86', 'Piotorax'],
    ['J90', 'Derrame pleural no clasificado en otra parte'],
    ['J91', 'Derrame pleural en afecciones clasificadas en otra parte'],
    ['J92', 'Paquipleuritis'],
    ['J93', 'Neumotorax'],
    ['J94', 'Otras afecciones de la pleura'],
    ['J95', 'Trastornos del sistema respiratorio consecutivos a procedimientos, no'],
    ['J96', 'Insuficiencia respiratoria, no clasificada en otra parte'],
    ['J98', 'Otros trastornos respiratorios'],
    ['J99', 'Trastornos respiratorios en enfermedades clasificadas en otra parte'],
    ['K00', 'Trastornos del desarrollo y de la erupción de los dientes'],
    ['K01', 'Dientes incluidos e impactados'],
    ['K02', 'Caries dental'],
    ['K03', 'Otras enfermedades de los tejidos duros de los dientes'],
    ['K04', 'Enfermedades de la pulpa y de los tejidos períapicales'],
    ['K05', 'Gingivitis y enfermedades periodontales'],
    ['K06', 'Otros trastornos de la encía y de la zona edéntula'],
    ['K07', 'Anomalías dentofaciales [incluso la maloclusión]'],
    ['K08', 'Otros trastornos de los dientes y de sus estructuras de sostén'],
    ['K09', 'Quistes de la región bucal, no clasificados en otra parte'],
    ['K10', 'Otras enfermedades de los maxilares'],
    ['K11', 'Enfermedades de las glándulas salivales'],
    ['K12', 'Estomatitis y lesiones afines'],
    ['K13', 'Otras enfermedades de los labios y de la mucosa bucal'],
    ['K14', 'Enfermedades de la lengua'],
    ['K20', 'Esofagitis'],
    ['K21', 'Enfermedad del reflujo gastroesofágico'],
    ['K22', 'Otras enfermedades del esófago'],
    ['K23', 'Trastornos del esófago en enfermedades clasificadas en otra parte'],
    ['K25', 'Úlcera gástrica'],
    ['K26', 'Úlcera duodenal'],
    ['K27', 'Úlcera péptica, de sitio no especificado'],
    ['K28', 'Úlcera gastroyeyunal'],
    ['K29', 'Gastritis y duodenitis'],
    ['K30', 'Dispepsia'],
    ['K31', 'Otras enfermedades del estómago y del duodeno'],
    ['K35', 'Apendicitis aguda'],
    ['K36', 'Otros tipos de apendicitis'],
    ['K37', 'Apendicitis, no especificada'],
    ['K38', 'Otras enfermedades del apéndice'],
    ['K40', 'Hernia inguinal'],
    ['K41', 'Hernia femoral'],
    ['K42', 'Hernia umbilical'],
    ['K43', 'Hernia ventral'],
    ['K44', 'Hernia diafragmática'],
    ['K45', 'Otras hernias de la cavidad abdominal'],
    ['K46', 'Hernia no especificada de la cavidad abdominal'],
    ['K50', 'Enfermedad de Crohn [enteritis regional]'],
    ['K51', 'Colitis ulcerativa'],
    ['K52', 'Otras colitis y gastroenteritis no infecciosas'],
    ['K55', 'Trastornos vasculares de los intestinos'],
    ['K56', 'Íleo paralítico y obstrucción intestinal sin hernia'],
    ['K57', 'Enfermedad diverticular del intestino'],
    ['K58', 'Síndrome del colon irritable'],
    ['K59', 'Otros trastornos funcionales del intestino'],
    ['K60', 'Fisura y fístula de las regiones anal y rectal'],
    ['K61', 'Absceso de las regiones anal y rectal'],
    ['K62', 'Otras enfermedades del ano y del recto'],
    ['K63', 'Otras enfermedades de los intestinos'],
    ['K65', 'Peritonitis'],
    ['K66', 'Otras Trastornos del peritoneo'],
    ['K67', 'Trastornos del peritoneo en enfermedades infecciosas clasificadas en otra parte'],
    ['K70', 'Enfermedad alcohólica del hígado'],
    ['K71', 'Enfermedad tóxica del hígado'],
    ['K72', 'Insuficiencia hepática, no clasificada en otra parte'],
    ['K73', 'Hepatitis crónica, no clasificada en otra parte'],
    ['K74', 'Fibrosis y cirrosis del hígado'],
    ['K75', 'Otras enfermedades inflamatorias del hígado'],
    ['K76', 'Otras enfermedades del hígado'],
    ['K77', 'Trastornos del hígado en enfermedades clasificadas en otra parte'],
    ['K80', 'Colelitiasis'],
    ['K81', 'Colecistitis'],
    ['K82', 'Otras enfermedades de la vesícula biliar'],
    ['K83', 'Otras enfermedades de las vías biliares'],
    ['K85', 'Pancreatitis aguda'],
    ['K86', 'Otras enfermedades del páncreas'],
    ['K87', 'Trastornos de la vesícula biliar, de las vías biliares y del páncreas en enfermedades clasificadas en otra parte'],
    ['K90', 'Malabsorción intestinal'],
    ['K91', 'Trastornos del sistema digestivo consecutivos a procedimientos, no clasificados en otra parte'],
    ['K92', 'Otras enfermedades del sistema digestivo'],
    ['K93', 'Trastornos de otros órganos digestivos en enfermedades clasificadas en otra parte'],
    ['L00', 'Síndrome estafilocócico de la piel escaldada'],
    ['L01', 'Impétigo'],
    ['L02', 'Absceso cutáneo, furúnculo y carbunco'],
    ['L03', 'Celulitis'],
    ['L04', 'Linfadenitis aguda'],
    ['L05', 'Quiste pilonidal'],
    ['L08', 'Otras infecciones locales de la piel y del tejido subcutáneo'],
    ['L10', 'Penfigo'],
    ['L11', 'Otros trastornos acantolíticos'],
    ['L12', 'Pénfigoide'],
    ['L13', 'Otros trastornos flictenulares'],
    ['L14', 'Trastornos flictenulares en enfermedades clasificadas en otra parte'],
    ['L20', 'Dermatitis atópica'],
    ['L21', 'Dermatitis seborreica'],
    ['L22', 'Dermatitis del pañal'],
    ['L23', 'Dermatitis alérgica de contacto'],
    ['L24', 'Dermatitis de contacto por irritantes'],
    ['L25', 'Dermatitis de contacto, forma no especificada'],
    ['L26', 'Dermatitis exfoliativa'],
    ['L27', 'Dermatitis debida a sustancias ingeridas'],
    ['L28', 'Liquen simple crónico y prurigo'],
    ['L29', 'Prurito'],
    ['L30', 'Otras dermatitis'],
    ['L40', 'Psoriasis'],
    ['L41', 'Parapsoriasis'],
    ['L42', 'Pitiriasis rosada'],
    ['L43', 'Liquen plano'],
    ['L44', 'Otros trastornos papuloescamosos'],
    ['L45', 'Trastornos papuloescamosos en enfermedades clasificadas en otra parte'],
    ['L50', 'Urticaria'],
    ['L51', 'Eritema multiforme'],
    ['L52', 'Eritema nudoso'],
    ['L53', 'Otras afecciones eritematosas'],
    ['L54', 'Eritema en enfermedades clasificadas en otra parte'],
    ['L55', 'Quemadura solar'],
    ['L56', 'Otros cambios agudos de la piel debidos a radiación ultravioleta'],
    ['L57', 'Cambios de la piel debidos a exposición crónica a radiación no ionizante'],
    ['L58', 'Radiodermatitis'],
    ['L59', 'Otros trastornos de la piel y del tejido subcutáneo relacionados con radiación'],
    ['L60', 'Trastornos de las uñas'],
    ['L62', 'Trastornos de las uñas en enfermedades clasificadas en otra parte'],
    ['L63', 'Alopecia areata'],
    ['L64', 'Alopecia androgénica'],
    ['L65', 'Otra pérdida no cicatricial del pelo'],
    ['L66', 'Alopecia cicatricial [pérdida cicatricial del pelo]'],
    ['L67', 'Anormalidades del tallo y del color del pelo'],
    ['L68', 'Hipertricosis'],
    ['L70', 'Cane'],
    ['L71', 'Rosácea'],
    ['L72', 'Quiste folicular de la piel y del tejido subcutáneo'],
    ['L73', 'Otros trastornos foliculares'],
    ['L74', 'Trastornos sudoríparos écrinos'],
    ['L75', 'Trastornos sudoríparos apocrinos'],
    ['L80', 'Vitíligo'],
    ['L81', 'Otros trastornos de la pigmentación'],
    ['L82', 'Queratosis seborreica'],
    ['L83', 'Acantosis nigricans'],
    ['L84', 'Callos y callosidades'],
    ['L85', 'Otros tipos de engrosamiento epidérmico'],
    ['L86', 'Queratodermia en enfermedades clasificadas en otra parte'],
    ['L87', 'Trastornos de la eliminación transepidermal'],
    ['L88', 'Pioderma gangrenoso'],
    ['L89', 'Úlcera de decúbito'],
    ['L90', 'Trastornos atróficos de la piel'],
    ['L91', 'Trastornos hipertróficos de la piel'],
    ['L92', 'Trastornos granulomatosos de la piel y del tejido subcutáneo'],
    ['L93', 'Lupus eritematoso'],
    ['L94', 'Otros trastornos localizados del tejido conjuntivo'],
    ['L95', 'Vasculitis limitada a la piel, no clasificada en otra parte'],
    ['L97', 'Úlcera de miembro inferior, no clasificada en otra parte'],
    ['L98', 'Otros trastornos de la piel y del tejido subcutáneo, no clasificados en otra parte'],
    ['L99', 'Otros trastornos de la piel y del tejido subcutáneo en enfermedades clasificadas en otra parte'],
    ['M00', 'Artritis piógena'],
    ['M01', 'Infecciones directas de la articulación en enfermedades infecciosas y parasitarias clasificadas en otra parte'],
    ['M02', 'Artropatías reactivas'],
    ['M03', 'Artropatías postinfecciosas y reactivas en enfermedades clasificadas en otra parte'],
    ['M05', 'Artritis reumatoide seropositiva'],
    ['M06', 'Otras artritis reumatoideas'],
    ['M07', 'Artropatías psoriásicas y enteropáticas'],
    ['M08', 'Artritis juvenil'],
    ['M09', 'Artritis juvenil en enfermedades clasificadas en otra parte'],
    ['M10', 'Gota'],
    ['M11', 'Otras artropatías por cristales'],
    ['M12', 'Otras artropatías específicas'],
    ['M13', 'Otras artritis'],
    ['M14', 'Artropatía en otras enfermedades clasificadas en otra parte'],
    ['M15', 'Poliartrosis'],
    ['M16', 'Coxartrosis [artrosis de la cadera]'],
    ['M17', 'Gonartrosis [artrosis de la rodilla]'],
    ['M18', 'Artrosis de la primera articulación carpometacarpiana'],
    ['M19', 'Otras artrosis'],
    ['M20', 'Deformidades adquiridas de los dedos de la mano y del pie'],
    ['M21', 'Otras deformidades adquiridas de los miembros'],
    ['M22', 'Trastornos de la rótula'],
    ['M23', 'Trastorno interno de la rodilla'],
    ['M24', 'Otros trastornos articulares específicos'],
    ['M25', 'Otros trastornos articulares, no clasificados en otra parte'],
    ['M30', 'Poliarteritis nudosa y afecciones relacionadas'],
    ['M31', 'Otras vasculopatías necrotizantes'],
    ['M32', 'Lupus eritematoso sistémico'],
    ['M33', 'Dermatopolimiositis'],
    ['M34', 'Esclerosis sistémica'],
    ['M35', 'Otro compromiso sistémico del tejido conjuntivo'],
    ['M36', 'Trastornos sistémicos del tejido conjuntivo en enfermedades clasificadas en otra parte'],
    ['M40', 'Cifosis y lordosis'],
    ['M41', 'Escoliosis'],
    ['M42', 'Osteocondrosis de la columna vertebral'],
    ['M43', 'Otras dorsopatías deformantes'],
    ['M45', 'Espondilitis anquilosante'],
    ['M46', 'Otras espondilopatías inflamatorias'],
    ['M47', 'Espondilosis'],
    ['M48', 'Otras espondilopatías'],
    ['M49', 'Espondilopatías en enfermedades clasificadas en otra parte'],
    ['M50', 'Trastornos de disco cervical'],
    ['M51', 'Otros trastornos de los discos intervertebrales'],
    ['M53', 'Otras dorsopatías, no clasificadas en otra parte'],
    ['M54', 'Dorsalgia'],
    ['M60', 'Miositis'],
    ['M61', 'Calcificación y osificación del músculo'],
    ['M62', 'Otros trastornos de los músculos'],
    ['M63', 'Trastornos de los músculos en enfermedades clasificadas en otra parte'],
    ['M65', 'Sinovitis y tenosinovitis'],
    ['M66', 'Ruptura espontánea de la sinovial y del tendón'],
    ['M67', 'Otros trastornos de la sinovial y del tendón'],
    ['M68', 'Trastornos de los tendones y de la sinovial en enfermedades clasificadas en otra parte'],
    ['M70', 'Trastornos de los tejidos blandos relacionados con el uso, el uso excesivo y la presión'],
    ['M71', 'Otras bursopatías'],
    ['M72', 'Trastornos fibroblásticos'],
    ['M73', 'Trastornos de los tejidos blandos en enfermedades clasificadas en otra parte'],
    ['M75', 'Lesiones del hombro'],
    ['M76', 'Entesopatías del miembro inferior, excluido el pie'],
    ['M77', 'Otras entesopatías'],
    ['M79', 'Otros trastornos de los tejidos blandos, no clasificados en otra parte'],
    ['M80', 'Osteoporosis con fractura patológica'],
    ['M81', 'Osteoporosis sin fractura patológica'],
    ['M82', 'Osteoporosis en enfermedades clasificadas en otra parte'],
    ['M83', 'Osteomalacia del adulto'],
    ['M84', 'Trastornos de la continuidad del hueso'],
    ['M85', 'Otros trastornos de la densidad y de la estructura óseas'],
    ['M86', 'Osteomielitis'],
    ['M87', 'Osteonecrosis'],
    ['M88', 'Enfermedad de Pagel de los huesos [osteítis deformante]'],
    ['M89', 'Otros trastornos del hueso'],
    ['M90', 'Osteopatías en enfermedades clasificadas en otra parte'],
    ['M91', 'Osteocondrosis juvenil de la cadera y de la pelvis'],
    ['M92', 'Otras osteocondrosis juveniles'],
    ['M93', 'Otras osteocondropatías'],
    ['M94', 'Otros trastornos del cartílago'],
    ['M95', 'Otras deformidades adquiridas del sistema osteomuscular y del tejido conjuntivo'],
    ['M96', 'Trastornos osteomusculares consecutivos a procedimientos, no clasificados en otra parte'],
    ['M99', 'Lesiones biomecánicas, no clasificadas en otra parte'],
    ['N00', 'Síndrome nefrítico agudo'],
    ['N01', 'Síndrome nefrítico rápidamente progresivo'],
    ['N02', 'Hematuria recurrente y persistente'],
    ['N03', 'Síndrome nefrítico crónico'],
    ['N04', 'Síndrome nefrótico'],
    ['N05', 'Síndrome nefrítico no especificado'],
    ['N06', 'Proteinuria aislada con lesión morfológica especificada'],
    ['N07', 'Nefropatía hereditaria, no clasificada en otra parte'],
    ['N08', 'Trastornos glomerulares en enfermedades clasificadas en otra parte'],
    ['N10', 'Nefritis tubulointersticial aguda'],
    ['N11', 'Nefritis tubulointersticial crónica'],
    ['N12', 'Nefritis tubulointersticial, no especificada como aguda o crónica'],
    ['N13', 'Uropatía obstructiva y por reflujo'],
    ['N14', 'Afecciones tubulares y tubulointersticiales inducidas por drogas y por metales pesados'],
    ['N15', 'Otras enfermedades renales tubulointersticiales'],
    ['N16', 'Trastornos renales tubulointersticiales en enfermedades clasificadas en otra parte'],
    ['N17', 'Insuficiencia renal aguda'],
    ['N18', 'Insuficiencia renal crónica'],
    ['N19', 'Insuficiencia renal no especificada'],
    ['N20', 'Cálculo del riñón y del uréter'],
    ['N21', 'Cálculo de las vías urinarias inferiores'],
    ['N22', 'Cálculo de las vías urinarias en enfermedades clasificadas en otra parte'],
    ['N23', 'Cólico renal, no especificado'],
    ['N25', 'Trastornos resultantes de la función tubular renal alterada'],
    ['N26', 'Rincón contraído, no especificado'],
    ['N27', 'Rincón pequeño de causa desconocida'],
    ['N28', 'Otros trastornos del riñón y del uréter, no clasificados en otra parte'],
    ['N29', 'Otros trastornos del riñón y del uréter en enfermedades clasificadas en otra parte'],
    ['N30', 'Cistitis'],
    ['N31', 'Disfunción neuromuscular de la vejiga, no clasificada en otra parte'],
    ['N32', 'Otros trastornos de la vejiga'],
    ['N33', 'Trastornos de la vejiga en enfermedades clasificadas en otra parte'],
    ['N34', 'Uretritis y síndrome uretral'],
    ['N35', 'Estrechez uretral'],
    ['N36', 'Otros trastornos de la uretra'],
    ['N37', 'Trastornos de la uretra en enfermedades clasificadas en otra parte'],
    ['N39', 'Otros trastornos del sistema urinario'],
    ['N40', 'Hiperplasia de la próstata'],
    ['N41', 'Enfermedades inflamatorias de la próstata'],
    ['N42', 'Otros trastornos de la próstata'],
    ['N43', 'Hidrocele y espermatocele'],
    ['N44', 'Torsión del testículo'],
    ['N45', 'Orquitis y epididimitis'],
    ['N46', 'Esterilidad en el varón'],
    ['N47', 'Prepucio redundante, fimosis y parafimosis'],
    ['N48', 'Otros trastornos del pene'],
    ['N49', 'Trastornos inflamatorios de órganos genitales masculinos, no clasificados en otra parte'],
    ['N50', 'Otros trastornos de los órganos genitales masculinos'],
    ['N51', 'Trastornos de los órganos genitales masculinos en enfermedades clasificadas en otra parte'],
    ['N60', 'Displasia mamaria benigna'],
    ['N61', 'Trastornos inflamatorios de la mama'],
    ['N62', 'Hipertrofia de la mama'],
    ['N63', 'Masa no especificada en la mama'],
    ['N64', 'Otros trastornos de la mama'],
    ['N70', 'Salpingitis y ooforitis'],
    ['N71', 'Enfermedad inflamatoria del útero, excepto del cuello uterino'],
    ['N72', 'Enfermedad inflamatoria del cuello uterino'],
    ['N73', 'Otras enfermedades pélvicas inflamatorias femeninas'],
    ['N74', 'Trastornos inflamatorios de la pelvis femenina en enfermedades clasificadas en otra parte'],
    ['N75', 'Enfermedades de la glándula de Bartholin'],
    ['N76', 'Otras afecciones inflamatorias de la vagina y de la vulva'],
    ['N77', 'Ulceración e inflamación vulvovaginal en enfermedades clasificadas en otra parte'],
    ['N80', 'Endometriosis'],
    ['N81', 'Prolapso genital femenino'],
    ['N82', 'Fístulas que afectan el tracto genital femenino'],
    ['N83', 'Trastornos no inflamatorios del ovario, de la trompa de Falopio y del ligamento ancho'],
    ['N84', 'Pólipo del tracto genital femenino'],
    ['N85', 'Otros trastornos no inflamatorios del útero, excepto del cuello'],
    ['N86', 'Erosión y ectropion del cuello del útero'],
    ['N87', 'Displasia del cuello uterino'],
    ['N88', 'Otros trastornos no inflamatorios del cuello del útero'],
    ['N89', 'Otros trastornos no inflamatorios de la vagina'],
    ['N90', 'Otros trastornos no inflamatorios de la vulva y del perineo'],
    ['N91', 'Menstruación ausente, escasa o rara'],
    ['N92', 'Menstruación excesiva, frecuente e irregular'],
    ['N93', 'Otras hemorragias uterinas o vaginales anormales'],
    ['N94', 'Dolor y otras afecciones relacionadas con los órganos genitales femeninos y con el ciclo menstrual'],
    ['N95', 'Otros trastornos menopáusicos y perimenopáusicos'],
    ['N96', 'Abortadora habitual'],
    ['N97', 'Infertilidad femenina'],
    ['N98', 'Complicaciones asociadas con la fecundación artificial'],
    ['N99', 'Trastornos del sistema genitourinario consecutivos a procedimientos, no clasificados en otra parte'],
    ['O00', 'Embarazo ectópico'],
    ['O01', 'Mola hidatiforme'],
    ['O02', 'Otros productos anormales de la concepción'],
    ['O03', 'Aborto espontáneo'],
    ['O04', 'Aborto médico'],
    ['O05', 'Otro aborto'],
    ['O06', 'Aborto no especificado'],
    ['O07', 'Intento fallido de aborto'],
    ['O08', 'Complicaciones consecutivas al aborto, al embarazo ectópico y al embarazo molar'],
    ['O10', 'Hipertensión preexistente que complica el embarazo, el parto y el puerperio'],
    ['O11', 'Trastornos hipertensivos preexistentes, con proteinuria agregada'],
    ['O12', 'Edema y proteinuria gestacionales [inducidos por el embarazo] sin hipertensión'],
    ['O13', 'Hipertensión gestacional [inducida por el embarazo] sin proteinuria significativa'],
    ['O14', 'Hipertensión gestacional [inducida por el embarazo] con proteinuria significativa'],
    ['O15', 'Eclampsia'],
    ['O16', 'Hipertensión materna, no especificada'],
    ['O20', 'Diabetes mellitus en el embarazo'],
    ['O21', 'Diabetes mellitus preexistente en el embarazo'],
    ['O22', 'Trastornos del metabolismo de los carbohidratos en el embarazo'],
    ['O23', 'Infección en el embarazo'],
    ['O24', 'Diabetes mellitus en trastornos endocrinos y metabólicos en el embarazo'],
    ['O25', 'Trastornos del sistema nervioso en el embarazo'],
    ['O26', 'Trastornos renales en el embarazo'],
    ['O28', 'Otras afecciones maternas relacionadas con el embarazo y con el aparato reproductor'],
    ['O30', 'Infección de las membranas y de los líquidos amnióticos en el embarazo'],
    ['O31', 'Otras enfermedades infecciosas específicas en el embarazo'],
    ['O32', 'Polihidramnios'],
    ['O33', 'Poliglobulia del recién nacido'],
    ['O34', 'Atención materna por presentación anormal del feto'],
    ['O35', 'Atención materna por malposición, presentación anormal y encajamiento del feto'],
    ['O36', 'Atención materna por signos reveladores de sufrimiento fetal'],
    ['O40', 'Polihidramnios'],
    ['O41', 'Oligohidramnios'],
    ['O42', 'Rotura prematura de las membranas'],
    ['O43', 'Placenta previa'],
    ['O44', 'Otras hemorragias placentarias'],
    ['O45', 'Desprendimiento prematuro de la placenta'],
    ['O46', 'Trabajo de parto preterminado'],
    ['O47', 'Trabajo de parto prolongado'],
    ['O48', 'Otras complicaciones del trabajo de parto y del parto'],
    ['O60', 'Parto prematuro'],
    ['O61', 'Trabajo de parto prolongado y complicaciones del trabajo de parto'],
    ['O62', 'Trabajo de parto obstruido debido a la desproporción cefalopélvica'],
    ['O63', 'Sufrimiento fetal durante el trabajo de parto y el parto'],
    ['O64', 'Trabajo de parto obstruido debido a la presentación anormal del feto'],
    ['O65', 'Trabajo de parto obstruido debido a otras causas'],
    ['O66', 'Trabajo de parto prolongado sin motivo aparente'],
    ['O67', 'Trabajo de parto prolongado debido a obesidad'],
    ['O68', 'Trabajo de parto prolongado debido a otros motivos'],
    ['O69', 'Trabajo de parto prolongado, no especificado'],
    ['O70', 'Desgarro perineal durante el parto'],
    ['O71', 'Hemorragia en el postparto'],
    ['O72', 'Ruptura uterina durante el trabajo de parto'],
    ['O73', 'Retención de la cabeza del feto y de los hombros'],
    ['O74', 'Otras complicaciones del trabajo de parto y del parto, no clasificadas en otra parte'],
    ['O75', 'Enfermedades infecciosas del sistema reproductor en el puerperio'],
    ['O76', 'Otras complicaciones del puerperio, no clasificadas en otra parte'],
    ['O77', 'Trastornos cerebrovasculares en el puerperio'],
    ['O80', 'Parto único espontáneo en hospital o en el lugar de atención médica'],
    ['O81', 'Parto único espontáneo en el domicilio'],
    ['O82', 'Parto por cesárea'],
    ['O83', 'Parto asistido (con fórceps o ventosa)'],
    ['O84', 'Otros tipos de parto único espontáneo'],
    ['O85', 'Sepsis puerperal'],
    ['O86', 'Otros trastornos puerperales infecciosos'],
    ['O87', 'Tromboflebitis en el puerperio'],
    ['O88', 'Otros trastornos venosos en el puerperio'],
    ['O89', 'Otras complicaciones del puerperio no clasificadas en otra parte'],
    ['O90', 'Hemorragia del puerperio'],
    ['O91', 'Complicaciones del puerperio por aparato urinario'],
    ['O92', 'Otras complicaciones del puerperio, no clasificadas en otra parte'],
    ['O94', 'Muerte fetal'],
    ['O95', 'Desproporción materna y fetal'],
    ['O96', 'Muerte materna'],
    ['O97', 'Muertes múltiples debidas al embarazo, al parto y al puerperio'],
    ['O98', 'Otras enfermedades maternas clasificadas en otra parte'],
    ['O99', 'Otras enfermedades obstétricas y las no especificadas'],
    ['O150', 'Preeclampsia'],
    ['O200', 'Amenaza de aborto'],
    ['O221', 'Varices Vulnerables'],
    ['O331', 'Macrosomia Fetal'],
    ['O335', 'ICP'],
    ['O341', 'Cesarea Anterior'],
    ['O410', 'Placenta previa sin hemorragia'],
    ['O411', 'Placenta con hemorragia'],
    ['O912', 'Mastitis'],
    ['O990', 'Anemia y gestacion'],
    ['P050', 'RCIU'],
    ['Q831', 'Mamas Supernumerarias'],
    ['R103', 'Dolor Abdominal bajo'],
    ['Z014', 'Control Ginecologico'],
    ['Z27', 'Certificado Medico'],
    ['Z30', 'Anticoncepcion'],
    ['Z32', 'Supervisión de embarazo en el que se espera un nacimiento único'],
    ['Z33', 'Supervisión de embarazo en el que se espera un nacimiento múltiple'],
    ['Z34', 'Supervisión de embarazo con alto riesgo de complicaciones maternas'],
    ['Z35', 'Supervisión de embarazo con alto riesgo de complicaciones fetales'],
    ['Z36', 'Supervisión de otros embarazos de alto riesgo'],
    ['Z37', 'Vigilancia de término del parto'],
    ['Z38', 'Parto único espontáneo'],
    ['Z39', 'Vigilancia de parto por otros motivos'],
    ['Z40', 'Encuentros para la atención médica y el examen de rutina después del parto'],
    ['Z41', 'Atención a las mujeres en relación con procedimientos de reproducción asistida'],
    ['Z42', 'Atención a las mujeres en relación con la lactancia'],
    ['Z48', 'Cuidados post cirugia'],
    ['Z51', 'Procedimientos para la planificación de la familia'],
    ['Z51', 'Encuentros para anticoncepción'],
    ['Z302', 'Ligadura de trompas'],
    ['Z320', 'Embarazo aun no confirmado'],
    ['Z321', 'Embarazo confirmado'],
];

    foreach($all as $a){

        Cie10::create([
            'codigo' => $a[0],
            'descripcion' => $a[1]
        ]);
    }

    }
}
